package com.example.demo.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "businesses")
public class Business {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@ApiModelProperty("Primary key")
	private Long id;

	@ApiModelProperty("The business'name")
	private String nameBusiness;
	
	@ApiModelProperty("Years of the businesscompany in the market")
	private Integer years;
	
	@ApiModelProperty("Number of employees in the business")
	private Integer numUsers;
	
	@ApiModelProperty("Number of products generated by the business")
	private Integer numProducts;
	
	@ApiModelProperty("The businesses' billing")
	private Integer billing = null;

	public Business() {}

	public Long getId() {
		return id;
	}

	public String getNameBusiness() {
		return nameBusiness;
	}

	public Integer getYears() {
		return years;
	}

	public Integer getNumUsers() {
		return numUsers;
	}

	public Integer getNumProducts() {
		return numProducts;
	}

	public Integer getBilling() {
		return billing;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setNameBusiness(String nameBusiness) {
		this.nameBusiness = nameBusiness;
	}

	public void setYears(Integer years) {
		this.years = years;
	}

	public void setNumUsers(Integer numUsers) {
		this.numUsers = numUsers;
	}

	public void setNumProducts(Integer numProducts) {
		this.numProducts = numProducts;
	}

	public void setBilling(Integer billing) {
		this.billing = billing;
	}

	@Override
	public String toString() {
		return "Business [id=" + id + ", nameBusiness=" + nameBusiness + ", years=" + years + ", numUsers=" + numUsers
				+ ", numProducts=" + numProducts + ", billing=" + billing + "]";
	}


}